spring:
  application:
    name: example-spring-ai-langchain

#  ai:
#    ollama:
#      embedding:
#        model: "gemma"
#      chat:
#        model: "gemma"
langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: mistral
